services:
  - type: web
    name: digitalmarketingbiz-bot
    env: python
    region: oregon
    plan: starter

    buildCommand: pip install -r requirements.txt

    # ðŸš« no startCommand here â€” Render will read your Procfile instead

    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_SHEET_WEBAPP_URL
        sync: false
      - key: ROOT_URL
        value: https://digitalmarketingbiz-bot.onrender.com
      - key: PORT
        value: 10000

    healthCheckPath: /
    autoDeploy: true
